# Generated by Django 4.1.5 on 2023-02-16 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(default=1.1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kura.position'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kura.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kura.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'position')},
            },
        ),
    ]
