# Generated by Django 4.1.5 on 2023-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kura', '0002_position_remove_candidate_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
