# Generated by Django 4.1.5 on 2023-05-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kura', '0004_alter_candidate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_set', to='kura.position'),
        ),
    ]
